"""add_source_type_source_id_to_transactions

Revision ID: 230f4b5c4bd6
Revises:
Create Date: 2026-05-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '230f4b5c4bd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')


def _unused_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_user_period', ['user_id', 'year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('card_expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'cuota'"))
        batch_op.create_index('idx_card_expenses_card_period', ['card_id', 'first_payment_year', 'first_payment_month'], unique=False)

    with op.batch_alter_table('inversiones', schema=None) as batch_op:
        batch_op.alter_column('notas_tesis',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index('idx_notificaciones_user_leida', ['user_id', 'leida'], unique=False)

    with op.batch_alter_table('pagos_prestamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capital_uva', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interes_uva', sa.Float(), nullable=True))
        batch_op.drop_column('seguro')

    with op.batch_alter_table('pagos_servicios', schema=None) as batch_op:
        batch_op.alter_column('forma_pago',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargos_mensuales', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('numero_operacion', sa.String(), nullable=True))
        batch_op.drop_column('seguro_mensual')

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('numero_cuenta',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('link_pago',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('monto_variable',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('shared_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobante', sa.Text(), nullable=True))

    with op.batch_alter_table('shared_groups', schema=None) as batch_op:
        batch_op.alter_column('is_virtual',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('join_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_shared_groups_join_token'), ['join_token'], unique=True)

    with op.batch_alter_table('shared_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_transactions_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index('idx_transactions_user_type_date', ['user_id', 'type', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('google_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('totp_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('totp_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('onboarding_done',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def _unused_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('onboarding_done',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('totp_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('google_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_index('idx_transactions_user_type_date')
        batch_op.drop_index('idx_transactions_user_date')
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('shared_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shared_participants_user_id'))

    with op.batch_alter_table('shared_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_groups_join_token'))
        batch_op.alter_column('join_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_virtual',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('shared_expenses', schema=None) as batch_op:
        batch_op.drop_column('comprobante')

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('monto_variable',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('link_pago',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('numero_cuenta',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seguro_mensual', sa.FLOAT(), nullable=True))
        batch_op.drop_column('numero_operacion')
        batch_op.drop_column('cargos_mensuales')

    with op.batch_alter_table('pagos_servicios', schema=None) as batch_op:
        batch_op.alter_column('forma_pago',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('pagos_prestamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seguro', sa.FLOAT(), nullable=True))
        batch_op.drop_column('interes_uva')
        batch_op.drop_column('capital_uva')
        batch_op.drop_column('cargos')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_notificaciones_user_leida')

    with op.batch_alter_table('inversiones', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('notas_tesis',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('card_expenses', schema=None) as batch_op:
        batch_op.drop_index('idx_card_expenses_card_period')
        batch_op.alter_column('expense_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'cuota'"))

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))
        batch_op.drop_index('idx_budgets_user_period')

    # ### end Alembic commands ###
