"""
Dataset curado de promociones bancarias argentinas.
Fuente: información pública de bancos y billeteras (Mayo 2025).
Sin API externa — datos mantenidos en código para máxima confiabilidad.
"""

DIAS_NOMBRE = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

CAT_ICON = {
    "Supermercados": "🛒",
    "Farmacias": "💊",
    "Combustible": "⛽",
    "Gastronomia": "🍽️",
    "Indumentaria": "👗",
    "Electronica": "📱",
    "Viajes": "✈️",
    "Entretenimiento": "🎬",
    "Salud": "🏥",
    "Educacion": "📚",
    "Otros": "🏷️",
}

PROMOS_GLOBALES = [
    # ── Banco Galicia ──────────────────────────────────────────────────────────
    {
        "id": "global-1",
        "nombre": "Galicia — Coto",
        "descripcion": "30% de reintegro en Coto con tarjeta Galicia",
        "categoria": "Supermercados",
        "dias_semana": [2],
        "descuento_pct": 30,
        "tope_reintegro": 2000,
        "medio_pago": "Tarjeta de débito / crédito Galicia",
        "notas": "Reintegro en cuenta en 30 días hábiles. Tope por cuenta.",
    },
    {
        "id": "global-2",
        "nombre": "Galicia — Carrefour",
        "descripcion": "25% de reintegro en Carrefour con tarjeta Galicia",
        "categoria": "Supermercados",
        "dias_semana": [1],
        "descuento_pct": 25,
        "tope_reintegro": 1500,
        "medio_pago": "Tarjeta de débito / crédito Galicia",
        "notas": "Válido en todas las sucursales y en línea.",
    },
    {
        "id": "global-3",
        "nombre": "Galicia — YPF",
        "descripcion": "20% de reintegro en YPF con tarjeta Galicia",
        "categoria": "Combustible",
        "dias_semana": [3, 4],
        "descuento_pct": 20,
        "tope_reintegro": 1200,
        "medio_pago": "Tarjeta de débito Galicia",
        "notas": "Válido en surtidor. No acumulable con otros descuentos.",
    },
    {
        "id": "global-4",
        "nombre": "Galicia — Farmacity",
        "descripcion": "15% de reintegro en Farmacity con tarjeta Galicia",
        "categoria": "Farmacias",
        "dias_semana": [0],
        "descuento_pct": 15,
        "tope_reintegro": 800,
        "medio_pago": "Tarjeta de crédito Galicia",
        "notas": "Incluye perfumería y cosmética.",
    },
    # ── BBVA ──────────────────────────────────────────────────────────────────
    {
        "id": "global-5",
        "nombre": "BBVA — Día",
        "descripcion": "25% de reintegro en supermercados Día con BBVA",
        "categoria": "Supermercados",
        "dias_semana": [3],
        "descuento_pct": 25,
        "tope_reintegro": 1800,
        "medio_pago": "Tarjeta de débito BBVA",
        "notas": "Solo con tarjeta de débito BBVA Cuenta DNI.",
    },
    {
        "id": "global-6",
        "nombre": "BBVA — Jumbo",
        "descripcion": "20% de reintegro en Jumbo con tarjeta BBVA",
        "categoria": "Supermercados",
        "dias_semana": [5],
        "descuento_pct": 20,
        "tope_reintegro": 2500,
        "medio_pago": "Tarjeta de crédito BBVA Visa",
        "notas": "Reintegro a los 30 días hábiles en tu cuenta.",
    },
    {
        "id": "global-7",
        "nombre": "BBVA — Dr. Ahorro",
        "descripcion": "20% de reintegro en Dr. Ahorro con tarjeta BBVA",
        "categoria": "Farmacias",
        "dias_semana": [2],
        "descuento_pct": 20,
        "tope_reintegro": 900,
        "medio_pago": "Tarjeta de débito o crédito BBVA",
        "notas": "Incluye medicamentos y artículos de perfumería.",
    },
    # ── Banco Nación ──────────────────────────────────────────────────────────
    {
        "id": "global-8",
        "nombre": "BNA — La Anónima",
        "descripcion": "30% de reintegro en La Anónima con tarjeta BNA",
        "categoria": "Supermercados",
        "dias_semana": [2],
        "descuento_pct": 30,
        "tope_reintegro": 2000,
        "medio_pago": "Tarjeta de débito BNA",
        "notas": "Exclusivo jubilados y pensionados: tope $3000.",
    },
    {
        "id": "global-9",
        "nombre": "BNA — Supermercados adheridos",
        "descripcion": "15% de reintegro en supermercados adheridos con BNA",
        "categoria": "Supermercados",
        "dias_semana": [1, 3],
        "descuento_pct": 15,
        "tope_reintegro": 1200,
        "medio_pago": "Tarjeta de crédito / débito BNA",
        "notas": "Incluye Vea y adheridos. Verificar sucursal.",
    },
    {
        "id": "global-10",
        "nombre": "BNA — Combustible YPF",
        "descripcion": "10% de descuento en YPF con tarjeta BNA",
        "categoria": "Combustible",
        "dias_semana": [0, 1, 2, 3, 4, 5, 6],
        "descuento_pct": 10,
        "tope_reintegro": 1000,
        "medio_pago": "Tarjeta de débito BNA",
        "notas": "Aplica con YPF Serviclub activo.",
    },
    # ── Naranja X ─────────────────────────────────────────────────────────────
    {
        "id": "global-11",
        "nombre": "Naranja X — Gastronomía",
        "descripcion": "30% de reintegro en restaurantes con Naranja X",
        "categoria": "Gastronomia",
        "dias_semana": [4],
        "descuento_pct": 30,
        "tope_reintegro": 1500,
        "medio_pago": "Tarjeta o QR Naranja X",
        "notas": "Solo con pago por app Naranja X en restaurantes adheridos.",
    },
    {
        "id": "global-12",
        "nombre": "Naranja X — Pedidos Ya",
        "descripcion": "25% de reintegro en Pedidos Ya con Naranja X",
        "categoria": "Gastronomia",
        "dias_semana": [5, 6],
        "descuento_pct": 25,
        "tope_reintegro": 1200,
        "medio_pago": "Tarjeta Naranja X",
        "notas": "Máximo 2 pedidos por semana.",
    },
    {
        "id": "global-13",
        "nombre": "Naranja X — Supermercados",
        "descripcion": "20% de reintegro en supermercados con Naranja X",
        "categoria": "Supermercados",
        "dias_semana": [0],
        "descuento_pct": 20,
        "tope_reintegro": 1800,
        "medio_pago": "Tarjeta Naranja X",
        "notas": "Incluye Coto y Carrefour. No acumulable.",
    },
    # ── HSBC ──────────────────────────────────────────────────────────────────
    {
        "id": "global-14",
        "nombre": "HSBC — Walmart",
        "descripcion": "20% de reintegro en Walmart con tarjeta HSBC",
        "categoria": "Supermercados",
        "dias_semana": [3],
        "descuento_pct": 20,
        "tope_reintegro": 2000,
        "medio_pago": "Tarjeta de crédito HSBC Visa / Mastercard",
        "notas": "No válido con otras promociones o cuotas sin interés.",
    },
    {
        "id": "global-15",
        "nombre": "HSBC — Disco / Vea",
        "descripcion": "25% de reintegro en Disco y Vea con tarjeta HSBC",
        "categoria": "Supermercados",
        "dias_semana": [1],
        "descuento_pct": 25,
        "tope_reintegro": 2200,
        "medio_pago": "Tarjeta de débito HSBC",
        "notas": "Reintegro acreditado en 15 días hábiles.",
    },
    # ── Santander ─────────────────────────────────────────────────────────────
    {
        "id": "global-16",
        "nombre": "Santander — Shell",
        "descripcion": "20% de reintegro en Shell con tarjeta Santander",
        "categoria": "Combustible",
        "dias_semana": [2, 5],
        "descuento_pct": 20,
        "tope_reintegro": 1500,
        "medio_pago": "Tarjeta de crédito Santander Visa",
        "notas": "Aplicable en combustibles y tienda Shell Select.",
    },
    {
        "id": "global-17",
        "nombre": "Santander — Farmacidad",
        "descripcion": "15% de reintegro en Farmacidad con tarjeta Santander",
        "categoria": "Farmacias",
        "dias_semana": [4],
        "descuento_pct": 15,
        "tope_reintegro": 700,
        "medio_pago": "Tarjeta de crédito o débito Santander",
        "notas": "Incluye medicamentos con receta y artículos de perfumería.",
    },
    {
        "id": "global-18",
        "nombre": "Santander — Easy",
        "descripcion": "30% de reintegro en Easy con Tarjeta Cencosud Santander",
        "categoria": "Otros",
        "dias_semana": [6],
        "descuento_pct": 30,
        "tope_reintegro": 3000,
        "medio_pago": "Tarjeta Cencosud Santander",
        "notas": "Solo en tiendas Easy adheridas.",
    },
    # ── Mercado Pago ──────────────────────────────────────────────────────────
    {
        "id": "global-19",
        "nombre": "Mercado Pago — Coto",
        "descripcion": "35% de reintegro en Coto pagando con Mercado Pago",
        "categoria": "Supermercados",
        "dias_semana": [2],
        "descuento_pct": 35,
        "tope_reintegro": 1500,
        "medio_pago": "QR / Tarjeta Mercado Pago",
        "notas": "Reintegro en Mercado Pago en 24-72hs.",
    },
    {
        "id": "global-20",
        "nombre": "Mercado Pago — Farmacity",
        "descripcion": "25% de reintegro en Farmacity con Mercado Pago",
        "categoria": "Farmacias",
        "dias_semana": [1, 4],
        "descuento_pct": 25,
        "tope_reintegro": 1000,
        "medio_pago": "QR Mercado Pago",
        "notas": "Presentar QR en caja. No acumulable con club de beneficios.",
    },
    {
        "id": "global-21",
        "nombre": "Mercado Pago — Combustible",
        "descripcion": "15% de reintegro en YPF y Axion con Mercado Pago",
        "categoria": "Combustible",
        "dias_semana": [0, 1, 2, 3, 4],
        "descuento_pct": 15,
        "tope_reintegro": 800,
        "medio_pago": "QR Mercado Pago",
        "notas": "Solo pago desde la app Mercado Pago en el surtidor.",
    },
    {
        "id": "global-22",
        "nombre": "Mercado Pago — Rappi",
        "descripcion": "20% de reintegro en Rappi con tarjeta Mercado Pago",
        "categoria": "Gastronomia",
        "dias_semana": [5, 6],
        "descuento_pct": 20,
        "tope_reintegro": 1200,
        "medio_pago": "Tarjeta Mercado Pago",
        "notas": "Máximo 1 uso por semana por usuario.",
    },
    # ── Banco Macro ───────────────────────────────────────────────────────────
    {
        "id": "global-23",
        "nombre": "Macro — Carrefour",
        "descripcion": "25% de reintegro en Carrefour con tarjeta Macro",
        "categoria": "Supermercados",
        "dias_semana": [0],
        "descuento_pct": 25,
        "tope_reintegro": 2000,
        "medio_pago": "Tarjeta de débito Macro",
        "notas": "Solo con débito. En sucursales Carrefour Express también.",
    },
    {
        "id": "global-24",
        "nombre": "Macro — Gastronomía",
        "descripcion": "20% de reintegro en restaurantes adheridos con Macro",
        "categoria": "Gastronomia",
        "dias_semana": [4, 5],
        "descuento_pct": 20,
        "tope_reintegro": 1500,
        "medio_pago": "Tarjeta de crédito Macro Visa",
        "notas": "Consultar lista de adheridos en app Macro.",
    },
    # ── ICBC ──────────────────────────────────────────────────────────────────
    {
        "id": "global-25",
        "nombre": "ICBC — Supermercados",
        "descripcion": "20% de reintegro en Coto y La Anónima con ICBC",
        "categoria": "Supermercados",
        "dias_semana": [3],
        "descuento_pct": 20,
        "tope_reintegro": 1500,
        "medio_pago": "Tarjeta de crédito ICBC Visa",
        "notas": "No válido con descuentos del punto de venta.",
    },
    # ── Ualá ──────────────────────────────────────────────────────────────────
    {
        "id": "global-26",
        "nombre": "Ualá — Supermercados",
        "descripcion": "15% de reintegro en supermercados adheridos con Ualá",
        "categoria": "Supermercados",
        "dias_semana": [1, 3],
        "descuento_pct": 15,
        "tope_reintegro": 1000,
        "medio_pago": "Tarjeta prepaga Ualá Mastercard",
        "notas": "Reintegro en billetera Ualá dentro de las 72hs.",
    },
    {
        "id": "global-27",
        "nombre": "Ualá — Entretenimiento",
        "descripcion": "20% de reintegro en entretenimiento y streaming con Ualá",
        "categoria": "Entretenimiento",
        "dias_semana": [5, 6],
        "descuento_pct": 20,
        "tope_reintegro": 600,
        "medio_pago": "Tarjeta Ualá Mastercard",
        "notas": "Incluye cines, Netflix y plataformas adheridas.",
    },
    # ── Personal Pay ──────────────────────────────────────────────────────────
    {
        "id": "global-28",
        "nombre": "Personal Pay — Gastronomía",
        "descripcion": "30% de reintegro en locales de gastronomía con Personal Pay",
        "categoria": "Gastronomia",
        "dias_semana": [3, 4],
        "descuento_pct": 30,
        "tope_reintegro": 1800,
        "medio_pago": "QR Personal Pay",
        "notas": "Solo con pago QR desde app Personal Pay.",
    },
]


def _enrich(promo: dict) -> dict:
    return {
        **promo,
        "icono": CAT_ICON.get(promo["categoria"], "🏷️"),
        "dias_nombres": [DIAS_NOMBRE[d] for d in promo["dias_semana"] if 0 <= d <= 6],
        "es_global": True,
    }


def get_todas() -> list:
    return [_enrich(p) for p in PROMOS_GLOBALES]


def get_promos_hoy(weekday: int) -> list:
    """weekday: 0=Lunes … 6=Domingo (convención Python)."""
    return [_enrich(p) for p in PROMOS_GLOBALES if weekday in p["dias_semana"]]
